openapi: 3.0.0
info:
  title: Notes API
  description: API for managing notes
  version: 1.0.0
servers:
  - url: https://api.notesapp.com/v1
paths:
  /notes:
    get:
      summary: Get all notes
      operationId: getNotes
      responses:
        '200':
          description: A list of notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      summary: Create a new note
      operationId: createNote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '201':
          description: Note created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
  /notes/{id}:
    get:
      summary: Get a note by ID
      operationId: getNoteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested note
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
    put:
      summary: Update a note by ID
      operationId: updateNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Note updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
    delete:
      summary: Delete a note by ID
      operationId: deleteNote
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Note deleted
        '404':
          description: Note not found
components:
  schemas:
    Note:
      type: object
      properties:
        id:
          type: string
          format: uuidv4
          example: "9e1e05d0-80b4-40e0-adb7-e5339135e304"
        title:
          type: string
          example: "Meeting Notes"
        content:
          type: string
          example: "Discuss project updates with the team."
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
